// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mweobrpnifqtxqslrbjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13ZW9icnBuaWZxdHhxc2xyYmpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDgxMjAsImV4cCI6MjA2MDI4NDEyMH0.4pCAIr0Eb63mjqOTWuEJg2OVgBs5I8GI-z0CT3HHhZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);